### PR TITLE
Implement Multiple remote deploys

### PR DESCRIPTION
**Pull request by Tarig0**
This should allow for serial remote deploys to be designated in a single task.

Would be nice if the commands could be created in parallel.

These changes are based on

https://github.com/Microsoft/vsts-rm-extensions/blob/master/Extensions/Common/DeploymentSDK/Src/InvokeRemoteDeployment.ps1#L105

### CODE REVIEW

**Comment by rschiefer** [comment]
This is a cool idea, thanks!

Would deployment groups in VSTS work for this use case?  I haven't used them personally but my understanding (may be wrong here) is you can use deployment groups to perform a set of tasks on multiple target servers.

image

So the target server on the MSDeployAllTheThings task would simply be "localhost" because the task would run on the server.

**Comment by Tarig0** [comment]
The deployment group is still in preview, but I believe once they get the feature released to on-prem they will work for this use case. 

I am stuck with the feature set in on-prem so they are not an option for my work

**Comment by Tarig0** [comment]
Added reference link to description

https://github.com/Microsoft/vsts-rm-extensions/blob/master/Extensions/Common/DeploymentSDK/Src/InvokeRemoteDeployment.ps1#L105

**Comment by rschiefer** [comment]
Knowing the deployment group functionality is on its way, I don't want to complicate this task further with multiple deployments.  Sorry :(

As a temporary workaround you can just add multiple tasks, one for each deployment.  I know its not ideal but should work.

**Comment by Tarig0** [comment]
I'll package my changes into it's own extension for my private use.

I know for my work group having agents on the web servers get some of our network admins nervous but hopefully I can convince them to use the feature when it is available

**Comment by Tarig0** [comment]
The more I think on this I believe that the canned IIS tasks built into vsts will overshadow this plugin task. At least for the local deploy on deployment groups.

**Pull request closed without merging**
